### DISCUSSION TITLE
How to add other cameras perspective in one robot

### DISCUSSION THREAD

**Discussion by ClorisUcas** [StanfordVL/BEHAVIOR-1K#1004] [Q&A] [answered]
Thanks for grate work!
I 'm trying to add another camera pespective in the robot by adding another "VisionSensor" in the configuration, but it seems like only support one camera in the robot. Besides, I use "enternal_sensor" to add a camera, but I only get a world view and cannot bind with the robot.
Hope for your useful solutions !!!

**Comment by hang-yin** [comment]
Hi @ClorisUcas , this is a great question! For example, here's how you can add a wrist camera to Fetch:
```
  external_sensors:
    - sensor_type: VisionSensor
      name: wrist_camera
      relative_prim_path: /controllable__fetch__robot0/wrist_roll_link/wrist_camera
      modalities: [rgb, depth]
      sensor_kwargs:
        image_height: 128
        image_width: 128
      position: [0, 0, 0.2]
      orientation: [0.707, 0.0, 0.0, 0.707]
      pose_frame: parent
```

You can specify how you want to position the camera in relation to the link on the robot with the position and orientation args. Please let me know if this works for you!
