### DISCUSSION TITLE
How to add more sensors without robots

### DISCUSSION THREAD

**Discussion by SresserS** [StanfordVL/BEHAVIOR-1K#1189] [General]
I just got one sensor using "cam = og.sim.viewer_camera", but I want to know how to get some other cameras to get multiview data.

**Comment by SresserS** [comment]
Please help me @cgokmen @hang-yin 🙏

**Comment by hang-yin** [comment]
Hi @SresserS , please take a look at the `external_sensors` config for OG environment. For example, it can look something like this:
```
env:
  external_sensors:                     # (None or list): If specified, list of sensor configurations for external sensors to add. Should specify sensor "type" and any additional kwargs to instantiate the sensor. Each entry should be the kwargs passed to @create_sensor, in addition to position, orientation
    - sensor_type: VisionSensor
      name: external_sensor0
      relative_prim_path: /external_sensor0
      modalities: [rgb, depth]
      sensor_kwargs:
        image_height: 128
        image_width: 128
      position: [0, 0, 1.0]
      orientation: [0.707, 0.0, 0.0, 0.707]
      pose_frame: parent
  ...
```
